### ISSUE TITLE
Co-Op portals are invisible 

### ISSUE THREAD

**Issue by SelynCatto** [xoxor4d/p2-rtx#21] opened 2024-11-27 22:52 UTC
The blue, purple, orange, and red portals are completely invisible in co-op mode

**Comment by WolfeStrider** [comment] 2024-11-27 23:25
This has already been reported on Trello

**Comment by SelynCatto** [comment] 2024-11-28 07:13
> This has already been reported on Trello

I am assuming the trello isn't public as it has not been linked anywhere, would it not be more efficient to have it linked as well?

**Comment by WolfeStrider** [comment] 2024-11-28 22:57
Already asked about that. We can't because Trello only allows ten people to be signed in to view at once so I'm going to move all bug reports over to GitHub

**Comment by WolfeStrider** [comment] 2024-12-02 18:38
This is a duplicate of #61

**Closed as not planned** 2024-12-03 17:00 UTC
