### ISSUE TITLE
glados room in sp_a2_core is too dark

### ISSUE THREAD

**Issue by ulsap** [xoxor4d/p2-rtx#92] opened 2024-11-29 08:36 UTC
![Снимок экрана 2024-11-29 113524](https://github.com/user-attachments/assets/f1b5c257-8147-4629-8d18-6a4b7e30a602)

**Comment by WolfeStrider** [comment] 2024-11-29 17:13
Duplicate of #42

**Closed as completed** 2024-11-29 17:54 UTC
Labels: duplicate, remix-mod, missing-implementation
