### ISSUE TITLE
Portals arn't correct for me.

### ISSUE THREAD

**Issue by theCertifiedHotdog** [xoxor4d/p2-rtx#14] opened 2024-11-21 23:26 UTC
When I shoot a portal or one opens automatically, it looks like it was drawn in MS Paint, it has a white back and a solid blue / orange oval that you cant see through. The water is also a purple ish color that also looks like it was drawn in MS Paint. 
![MS Paint ahh portal](https://github.com/user-attachments/assets/49ac98c2-5a92-4956-8b43-8dbb36192cf5)
![MS Paint ahh water](https://github.com/user-attachments/assets/125146f3-04a5-42c6-ae18-c09a1b340975)

**Comment by xoxor4d** [comment] 2024-11-22 08:55
Duplicate of #13

**Closed as completed by xoxor4d** 2024-11-22 08:55 UTC
Labels: duplicate
